

const Services = () => {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam saepe sit tempore facilis pariatur exercitationem, laudantium alias accusantium veritatis natus aut repudiandae molestiae unde enim. Libero, ab? Ipsam assumenda soluta eos, fugiat porro fugit temporibus illo facilis ducimus omnis voluptas ad, corporis quos numquam possimus atque quaerat libero aspernatur quisquam? Suscipit illo magnam numquam animi nisi reprehenderit cumque magni accusamus officiis sint asperiores veniam expedita, similique sequi deleniti ea, obcaecati laboriosam repellendus veritatis qui laborum omnis dolores. Officia, laborum? Magnam dicta eius quae praesentium maxime voluptatem. Aliquam vel, voluptates saepe, sequi est, quo laboriosam sed vitae dignissimos velit nemo! Atque excepturi autem delectus laudantium iure sapiente consequatur labore nemo, beatae mollitia, optio, sit consectetur placeat repellat? Dolorum quo, ipsam alias quod animi laudantium nesciunt adipisci? Iure similique quo accusantium sit tempora aliquid minus, nam veritatis harum suscipit incidunt repellendus facere optio asperiores amet, ducimus eius. Quia hic vero esse animi soluta inventore commodi repudiandae error eveniet omnis qui veritatis porro, dolorum ratione labore ex neque impedit quod voluptatibus dicta! Reprehenderit vel illum voluptatum inventore, eligendi tempore maiores, sapiente consequatur animi modi deserunt similique architecto, neque ullam nostrum iure fugit eum delectus autem quaerat fugiat sunt incidunt maxime expedita. Iure, sit!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam saepe sit tempore facilis pariatur exercitationem, laudantium alias accusantium veritatis natus aut repudiandae molestiae unde enim. Libero, ab? Ipsam assumenda soluta eos, fugiat porro fugit temporibus illo facilis ducimus omnis voluptas ad, corporis quos numquam possimus atque quaerat libero aspernatur quisquam? Suscipit illo magnam numquam animi nisi reprehenderit cumque magni accusamus officiis sint asperiores veniam expedita, similique sequi deleniti ea, obcaecati laboriosam repellendus veritatis qui laborum omnis dolores. Officia, laborum? Magnam dicta eius quae praesentium maxime voluptatem. Aliquam vel, voluptates saepe, sequi est, quo laboriosam sed vitae dignissimos velit nemo! Atque excepturi autem delectus laudantium iure sapiente consequatur labore nemo, beatae mollitia, optio, sit consectetur placeat repellat? Dolorum quo, ipsam alias quod animi laudantium nesciunt adipisci? Iure similique quo accusantium sit tempora aliquid minus, nam veritatis harum suscipit incidunt repellendus facere optio asperiores amet, ducimus eius. Quia hic vero esse animi soluta inventore commodi repudiandae error eveniet omnis qui veritatis porro, dolorum ratione labore ex neque impedit quod voluptatibus dicta! Reprehenderit vel illum voluptatum inventore, eligendi tempore maiores, sapiente consequatur animi modi deserunt similique architecto, neque ullam nostrum iure fugit eum delectus autem quaerat fugiat sunt incidunt maxime expedita. Iure, sit!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam saepe sit tempore facilis pariatur exercitationem, laudantium alias accusantium veritatis natus aut repudiandae molestiae unde enim. Libero, ab? Ipsam assumenda soluta eos, fugiat porro fugit temporibus illo facilis ducimus omnis voluptas ad, corporis quos numquam possimus atque quaerat libero aspernatur quisquam? Suscipit illo magnam numquam animi nisi reprehenderit cumque magni accusamus officiis sint asperiores veniam expedita, similique sequi deleniti ea, obcaecati laboriosam repellendus veritatis qui laborum omnis dolores. Officia, laborum? Magnam dicta eius quae praesentium maxime voluptatem. Aliquam vel, voluptates saepe, sequi est, quo laboriosam sed vitae dignissimos velit nemo! Atque excepturi autem delectus laudantium iure sapiente consequatur labore nemo, beatae mollitia, optio, sit consectetur placeat repellat? Dolorum quo, ipsam alias quod animi laudantium nesciunt adipisci? Iure similique quo accusantium sit tempora aliquid minus, nam veritatis harum suscipit incidunt repellendus facere optio asperiores amet, ducimus eius. Quia hic vero esse animi soluta inventore commodi repudiandae error eveniet omnis qui veritatis porro, dolorum ratione labore ex neque impedit quod voluptatibus dicta! Reprehenderit vel illum voluptatum inventore, eligendi tempore maiores, sapiente consequatur animi modi deserunt similique architecto, neque ullam nostrum iure fugit eum delectus autem quaerat fugiat sunt incidunt maxime expedita. Iure, sit!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam saepe sit tempore facilis pariatur exercitationem, laudantium alias accusantium veritatis natus aut repudiandae molestiae unde enim. Libero, ab? Ipsam assumenda soluta eos, fugiat porro fugit temporibus illo facilis ducimus omnis voluptas ad, corporis quos numquam possimus atque quaerat libero aspernatur quisquam? Suscipit illo magnam numquam animi nisi reprehenderit cumque magni accusamus officiis sint asperiores veniam expedita, similique sequi deleniti ea, obcaecati laboriosam repellendus veritatis qui laborum omnis dolores. Officia, laborum? Magnam dicta eius quae praesentium maxime voluptatem. Aliquam vel, voluptates saepe, sequi est, quo laboriosam sed vitae dignissimos velit nemo! Atque excepturi autem delectus laudantium iure sapiente consequatur labore nemo, beatae mollitia, optio, sit consectetur placeat repellat? Dolorum quo, ipsam alias quod animi laudantium nesciunt adipisci? Iure similique quo accusantium sit tempora aliquid minus, nam veritatis harum suscipit incidunt repellendus facere optio asperiores amet, ducimus eius. Quia hic vero esse animi soluta inventore commodi repudiandae error eveniet omnis qui veritatis porro, dolorum ratione labore ex neque impedit quod voluptatibus dicta! Reprehenderit vel illum voluptatum inventore, eligendi tempore maiores, sapiente consequatur animi modi deserunt similique architecto, neque ullam nostrum iure fugit eum delectus autem quaerat fugiat sunt incidunt maxime expedita. Iure, sit!</p>
        </div>
    );
};

export default Services;